# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(376, 295)
        MainWindow.setMinimumSize(QtCore.QSize(376, 295))
        MainWindow.setMaximumSize(QtCore.QSize(376, 295))
        font = QtGui.QFont()
        font.setPointSize(8)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.heading = QtWidgets.QLabel(self.centralwidget)
        self.heading.setEnabled(True)
        self.heading.setGeometry(QtCore.QRect(140, 10, 91, 21))
        self.heading.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.heading.setFont(font)
        self.heading.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.heading.setMouseTracking(True)
        self.heading.setAutoFillBackground(True)
        self.heading.setAlignment(QtCore.Qt.AlignCenter)
        self.heading.setObjectName("heading")
        self.add_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_button.setGeometry(QtCore.QRect(50, 60, 101, 31))
        self.add_button.setObjectName("add_button")
        self.remove_button = QtWidgets.QPushButton(self.centralwidget)
        self.remove_button.setGeometry(QtCore.QRect(220, 60, 101, 31))
        self.remove_button.setObjectName("remove_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 110, 211, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.subred_drop = QtWidgets.QComboBox(self.centralwidget)
        self.subred_drop.setGeometry(QtCore.QRect(230, 110, 131, 22))
        self.subred_drop.setObjectName("subred_drop")
        self.subred_drop.addItem("")
        self.subred_drop.addItem("")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(130, 150, 101, 31))
        self.submit.setObjectName("submit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 190, 47, 14))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 210, 47, 14))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 230, 47, 14))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 250, 47, 14))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 270, 61, 16))
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.heading.setText(_translate("MainWindow", "r/stats"))
        self.add_button.setText(_translate("MainWindow", "Add Subreddit"))
        self.remove_button.setText(_translate("MainWindow", "Remove Subreddit"))
        self.label.setText(_translate("MainWindow", "Get recent top comment of: r/"))
        self.subred_drop.setItemText(0, _translate("MainWindow", "datascience"))
        self.subred_drop.setItemText(1, _translate("MainWindow", "MachineLearning"))
        self.submit.setText(_translate("MainWindow", "Go"))
        self.label_2.setText(_translate("MainWindow", "#:"))
        self.label_3.setText(_translate("MainWindow", "Titile:"))
        self.label_4.setText(_translate("MainWindow", "Author:"))
        self.label_5.setText(_translate("MainWindow", "Likes:"))
        self.label_6.setText(_translate("MainWindow", "Comments:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
